name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sreiser/otree:latest
    - name: Docker Push
      run: docker push sreiser/otree:latest
    - name: Azure WebHook POST Action
      uses: muinmomin/webhook-action@v1.0.0
      env:
        WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
      with:
        url: $WEBHOOK_URL
